---

- name: register lsb release
  command: lsb_release -cs
  register: lsb_release

- name: import Mongodb public key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7F0CEB10

- name: add mongodb deb repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ lsb_release.stdout }}/mongodb-org/3.0 multiverse"
    state: present

- name: install mongodb
  apt:
    name: mongodb-org
    state: present
