---

- name: install apache2
  apt:
    pkg: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - apache2
    - libapache2-mod-jk

- name: enables apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - headers
    - rewrite