---

- name: generate tomcat config file
  template:
    src: etc/default/tomcat7.j2
    dest: /etc/default/tomcat7
  notify: restart tomcat7

- name: generate tomcat server config to open port 8009
  template:
    src: etc/tomcat7/server.xml.j2
    dest: /etc/tomcat7/server.xml
  notify: restart tomcat7

# Enable remote debug
- name: create directory for setenv script
  file:
    path: /var/lib/tomcat7/bin
    state: directory

- name: generate script for setting JVM env variable to open debug port
  template:
    src: var/lib/tomcat7/bin/setenv.sh.j2
    dest: /var/lib/tomcat7/bin/setenv.sh
  notify: restart tomcat7

- name: generate init script for tomcat to enable debug
  template:
    src: etc/init.d/tomcat7.j2
    dest: /etc/init.d/tomcat7
  notify: restart tomcat7