---

- name: add db for app discovery server
  become_user: postgres
  delegate_to: "{{ groups['db']|first }}"
  postgresql_db:
    name: "{{ api_server_db }}"
    state: present

- name: add db user for app discovery server
  become_user: postgres
  delegate_to: "{{ groups['db']|first }}"
  postgresql_user:
    name: "{{ api_server_db_user }}"
    password: "{{ api_server_db_password }}"
    db: "{{ api_server_db }}"
    state: present
